<?php

namespace AppBundle\Repository;

/**
 * FormRequestRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
