<?php

namespace AppBundle\Repository;

/**
 * FormRequestTypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormRequestTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
