<?php

namespace AppBundle\Repository;

/**
 * SurveyRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSurveyByStatus($status)
    {
        $query = $this->createQueryBuilder('s')
            ->where('s.status = :status')
            ->setParameter('status', $status)
            ->orderBy('s.updatedAt', 'DESC')
            ->getQuery();

        return $query->getResult();
    }

    public function findSurveyByUser($user)
    {
        $query = $this->createQueryBuilder('s')
            ->where('s.user = :user')
            ->setParameter('user', $user)
            ->orderBy('s.updatedAt', 'DESC')
            ->getQuery();

        return $query->getResult();
    }
}
