<?php

namespace AppBundle\Repository;

/**
 * SurveyAnswerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyAnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAnswersBySurvey($survey)
    {
        $query = $this->createQueryBuilder('a')
            ->where('a.survey = :survey')
            ->setParameter('survey', $survey)
            ->getQuery();

        return $query->getResult();
    }
}
