<?php

namespace AppBundle\Repository;

/**
 * SurveyTypeSectionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyTypeSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
