<?php

namespace AppBundle\Repository;

/**
 * RequestTypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyQuestionContentRepository extends \Doctrine\ORM\EntityRepository
{
}
