<?php

namespace AppBundle\Repository;

/**
 * SurveyQuestionChoiceRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyQuestionChoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
