<?php

namespace AppBundle\Repository;

/**
 * UserSupervisorRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSupervisorRepository extends \Doctrine\ORM\EntityRepository
{
}
