<?php

namespace AppBundle\Repository;

/**
 * UserInternRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInternRepository extends \Doctrine\ORM\EntityRepository
{
}
