app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /logout

api:
    resource: "@AppBundle/Controller/Api/"
    type:     annotation
    prefix:   /api

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"