security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        api_provider:
            entity: { class: AppBundle:User }

        web_provider:
            entity: { class: AppBundle:Admin, property: email }

    firewalls:
        api:
            provider: api_provider
            anonymous: ~
            pattern: ^/api/
            stateless: true
            guard:
                authenticators:
                    - app.api_token_authenticator

        main:
            provider: web_provider
            anonymous: true
            security: true
            form_login:
                login_path: login
                check_path: login
                default_target_path: /

            logout:
                path:   /logout
                target: /login

    access_control:
          - { path: /login, allow_if: "is_anonymous() and !is_authenticated()" }
          - { path: ^/, roles: ROLE_USER_SUPERVISOR }
          - { path: ^/api/login$, allow_if: "not has_role('ROLE_USER_INTERN')" }
          - { path: ^/api/, roles: ROLE_USER_INTERN }


