security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        web_provider:
            entity: { class: AppBundle:UserSupervisor, property: userName }

    firewalls:

        api:
            anonymous: ~
            pattern: ^/api/
            stateless: true
            guard:
                authenticators:
                    - app.api_token_authenticator

        main:
            provider: web_provider
            anonymous: true
            pattern: /
            security: true
            form_login:
                login_path: login
                check_path: login

            logout:
                path:   /logout
                target: /login

    access_control:
          - { path: /api/login$, allow_if: "not has_role('ROLE_USER_INTERN')" }
          - { path: ^/api/, roles: ROLE_USER_INTERN }

