security:
    encoders:
        AppBundle\Entity\User: bcrypt
        AppBundle\Entity\Admin: bcrypt

    providers:
        api_provider:
            entity: { class: AppBundle:User }

        web_provider:
            entity: { class: AppBundle:Admin, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            provider: api_provider
            anonymous: ~
            pattern: ^/api
            stateless: true
            security: true
            guard:
                authenticators:
                    - app.api_token_authenticator

        main:
            http_basic: ~
            provider: web_provider
            anonymous: ~
            security: true
            form_login:
                login_path: login
                check_path: login
                default_target_path: /

            logout:
                path:   /logout
                target: /login
            http_basic: ~

    access_control:
          - { path: ^/api/login$, role:  IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/api/password_reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/api/password_update, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/api, roles: ROLE_USER }
          - { path: ^/login$, allow_if: "is_anonymous() and !is_authenticated()" }
          - { path: ^/, role:  ROLE_ADMIN }