security:
    encoders:
        AppBundle\Entity\User: bcrypt
        AppBundle\Entity\Admin: bcrypt

    providers:
        api_provider:
            entity: { class: AppBundle:User }

        web_provider:
            entity: { class: AppBundle:Admin, property: email }

    firewalls:
        api:
            provider: api_provider
            anonymous: ~
            pattern: ^/api/
            stateless: true
            guard:
                authenticators:
                    - app.api_token_authenticator

        main:
            provider: web_provider
            anonymous: ~
            pattern: ^/
            security: true
            form_login:
                login_path: login
                check_path: login

            logout:
                path:   /logout
                target: /login

    access_control:
          - { path: ^/$, roles: ROLE_ADMIN }
          - { path: ^/login$, allow_if: "is_anonymous() and !is_authenticated()" }
          - { path: ^/api/$, roles: ROLE_USER }
          - { path: ^/api/login$, allow_if: "is_anonymous() and !is_authenticated()" }


