# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
      app.api_token_authenticator:
          class: AppBundle\Security\ApiTokenAuthenticator
          arguments: ["@doctrine.orm.entity_manager"]


      app.doctrine_listener:
          class: AppBundle\Security\PasswordListener
          arguments: ['@security.password_encoder']
          tags:
              - { name: doctrine.event_subscriber }
