# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

      app.json_exception_listener:
          class: AppBundle\Listener\JsonExceptionListener
          arguments:
              - "@logger"
          tags:
              - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'onKernelException' }

      app.google_calendar_factory:
          class: AppBundle\Services\GoogleClientFactory
          arguments: ['%google_credentials_path%']

      app.google_calendar:
          class: AppBundle\Services\GoogleCalendarManager
          autowire: true

      app.api_token_authenticator:
          class: AppBundle\Security\ApiTokenAuthenticator

      app.doctrine_listener:
          class: AppBundle\Security\PasswordListener
          arguments: ['@security.password_encoder']
          tags:
              - { name: doctrine.event_subscriber }